version: '3'

services:
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env

  mongodb:
    image: "mongo:latest"
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file:
      - .env

  celery_worker:
    build: .
    volumes:
      - .:/app
    environment:
      - C_FORCE_ROOT=true
      - CELERY_BROKER_URL=amqp://guest:guest@rabbit:5672//
      - CELERY_RESULT_BACKEND=mongodb://mongodb:27017/celery_backend
      - CELERY_TASK_TRACK_STARTED=True
    depends_on:
      - rabbit
      - mongodb
    env_file:
      - .env

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    depends_on:
      - rabbit
      - mongodb
      - celery_worker
    env_file:
      - .env
