version: '3'

services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  celery:
    build: .
    command: celery -A tasks worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis

  fastapi:
    build: .
    command: uvicorn app:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    depends_on:
      - redis
      - celery
    ports:
      - "8000:8000"
