version: '3'

services:
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  mongodb:
    image: "mongo:latest"
    container_name: mongodb
    ports:
      - "27017:27017"

  celery_worker:
    build: .
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbit:5672//
      - CELERY_RESULT_BACKEND=mongodb://mongodb:27017/celery_backend
    depends_on:
      - rabbit
      - mongodb
